### ISSUE TITLE
bzlmod doesnot support "Exporting and consuming artifacts from external repositories"

### ISSUE THREAD

**Issue by crackit** [bazelbuild/rules_jvm_external#1169]
# user_project/WORKSPACE
load("@my_library//:library_deps.bzl", "MY_LIBRARY_ARTIFACTS")

maven_install(
  artifacts = [
        "junit:junit:4.11",
        "com.google.guava:guava:26.0-jre",
  ] + MY_LIBRARY_ARTIFACTS,
)

How does bzlmod support this?

**Comment by shs96c** [comment]
`bzlmod` supports this by "layering" `install` tags with the same `name` from multiple different projects. When this happens, we emit a warning on the console so that you're aware of where each of the artifacts that contribute to the resolution come from.

Put another way, for each `maven.install` in each `MODULE.bazel` file with the same `name` attribute, we gather all the `artifacts` and combine them together.
