### ISSUE TITLE
Downloads aren't retried when repositories return 503

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_jvm_external#129]
When I have a list of multiple repositories in our `maven_install` call, if the first URL returns a 503, it doesn't fall back to trying the second URL. Instead the build fails with this error:

```
ERROR: .../BUILD.bazel:5:1: no such package '@maven//': Error while fetching artifact with coursier:   Error:
https://...org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0/kotlin-stdlib-common-1.3.0.jar: DownloadError(Caught java.io.IOException: Server returned HTTP response code: 503 for URL: https://...org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0/kotlin-stdlib-common-1.3.0.jar (Server returned HTTP response code: 503 for URL: https://...org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0/kotlin-stdlib-common-1.3.0.jar) while downloading https://...org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0/kotlin-stdlib-common-1.3.0.jar)
```

If I comment out the URL that's currently 503ing, the build passes

**Comment by jin** [comment]
Currently, we pass a plain list of artifacts and repositories to coursier, so this will probably require Coursier to not fail on 503.

**Comment by jin** [comment]
I'm adding support for mirror urls when using pinned artifacts: https://github.com/bazelbuild/rules_jvm_external/pull/207

If you have connection reliability issues, I highly recommend switching to pinned artifacts instead of relying on Coursier's downloader, which doesn't fall back to second URLs. The issue still exists for the initial bootstrap fetch, but we can track that in https://github.com/coursier/coursier/issues/1135.
