### ISSUE TITLE
Duplicate JARs when using multiple maven_install

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_jvm_external#252]
# Problem
Let's say I have targets: `A` binary and `B` library. `A` depends on `B`. `B` depends on `@maven//:foo` which delgates to `foo:1.0` and `A` depends on `@maven2//:foo`, which delegates to `foo:2.0`.

When building `A`, the script that gets generated will include both `foo:1.0` and `foo:2.0` jars into the classpath.

Is there a way to avoid this other than defining both jars in the same `maven_install`? If not, what is the recommended way of upgrading 3rd party dependencies?

**Comment by jin** [comment]
You shouldn't mix foo:1.0 and foo:2.0 in the same dependency tree. Ideally, your entire transitive dependency should use jars from a single `@maven`/`maven_install` repository.

Is it possible for your build to use a single version of `foo`?

**Comment by KaoruDev** [comment]
hey, @jin thanks for the quick response!

You're right, ideally, we should only be using 1 version of `foo`. Alas, there are two scenarios where it may be difficult to do this:

1. If we wanted to do a rolling migration of a library binary by binary.
2. When migrating over to Bazel we discover a binary is using a dependency which is transitively pulling in a newer version of the library. Upgrading to the new version will break unrelated binaries using the same `maven_install` repository.

I think we all can agree that the correct thing to do in scenario #2 is to update the other binaries to use the newer version or somehow "shade" the binary pulling in the newer version. But I think in reality build engineers have little or no context of the product code and getting help from the product team could take a significant amount of time, depending on your org structure.

**Comment by jin** [comment]
This is unfortunately a Bazel "one-version" issue instead of a rules_jvm_external issue. Even without rules_jvm_external, it's possible for your build to bring in multiple versions of `foo` and run into classpath conflicts.

There's some internal wiring in Bazel ([`OneVersionEnforcementLevel`](https://github.com/bazelbuild/bazel/blob/38af41d2645e751808b185992709706c9d278443/src/main/java/com/google/devtools/build/lib/rules/java/JavaOptions.java#L490)), but it's not completely wired up and functional. 

What's the minimum thing that rules_jvm_external can do for you to make your migrations easier?

**Comment by KaoruDev** [comment]
Ah great, thank you for the context! I think I'm starting to understand the role `rules_jvm_external` plays in the Bazel world. I see now that this issue doesn't really fit in this project.
