### ISSUE TITLE
performance vs bazel-deps

### ISSUE THREAD

**Issue by joprice** [bazelbuild/rules_jvm_external#312]
I am comparing this project to https://github.com/johnynek/bazel-deps, and have noticed that updating a repository takes much longer than with bazel-deps. With bazel-deps, changing a single dependency version only takes a few seconds, whereas rules_jvm_external takes many minutes. Is this a know issue with the design, or perhaps something that could be improved upon?

**Comment by joprice** [comment]
I was able to narrow this down to the generation of sha256 hashes, since it runs a jvm per file. I modified it to take a list of arguments and return the results in a similar format to shasum. This brought the time down to a few seconds. I then used the parallel streams api to cut the time to under a second for around 400 dependencies. If this seems like a reasonable change, I can pr it and work through whatever testing is necessary:

https://github.com/bazelbuild/rules_jvm_external/compare/master...joprice:hashPerf

**Comment by jin** [comment]
@joprice thanks for discovering that optimization. Happy to take a PR!

**Comment by jin** [comment]
There's still a bunch of optimizations we can do here, like https://github.com/coursier/coursier/issues/1223 that doesn't require Coursier to download jars to generate the JSON tree. 

Closing this for now, as your PR has vastly improved the speed for artifact pinning. Thanks again.

**Comment by joprice** [comment]
I know scala so maybe I could pitch in there too. I'm not sure I understand the exact change required.

**Comment by jin** [comment]
We use the output of [`coursier fetch --json-output-file`](https://github.com/bazelbuild/rules_jvm_external/blob/b0c23d8260a0b3aff27982a0bc2f397919a84aea/coursier.bzl#L458) as the [source of truth for the dependency tree](https://github.com/bazelbuild/rules_jvm_external/blob/b0c23d8260a0b3aff27982a0bc2f397919a84aea/coursier.bzl#L490-L493), and the generated BUILD file. This flag is only supported with `coursier fetch`, not `coursier resolve`. `fetch` downloads jars, but `resolve` doesn't. It'll be nice to not have to download jars in order to generate the json output file.
