### ISSUE TITLE
Support annotation processing java_plugin targets 

### ISSUE THREAD

**Issue by senpo** [bazelbuild/rules_jvm_external#38]
I'm curious whether there is a plan to support the annotation processing for libraries such as [Dagger](https://github.com/google/dagger) and [AutoValue](https://github.com/google/auto/tree/master/value). 

The example BUILD file looks like this:
https://github.com/google/bazel-common/blob/master/third_party/java/auto/BUILD

[bazel_maven_repository](https://github.com/square/bazel_maven_repository) has this nice capability to customize the BUILD file for artifacts: https://github.com/square/bazel_maven_repository#substitution-of-build-targets

Thank you!

**Comment by jin** [comment]
I'm not sure if this is something we want to support in the `maven_install` tool. It does its one purpose well: resolving transitive artifacts and expose targets to a Bazel build. 

Adding special casing for annotation processing in the BUILD file generation logic increases the API surface layer, which I'm hesitant to add. 

Currently, you can use annotation processing writing your own `java_plugin` targets using the jars `maven_install` downloaded for you. This clarifies the single responsibility principle for the repository rule, because it doesn't need to know anything about annotation processing.

@dkelmer thoughts?

**Comment by senpo** [comment]
That absolutely makes sense to keep this tool single purposed. I love the simplicity of the transitive artifacts resolution. Nice work, thanks!
