### ISSUE TITLE
Maven artifact export and publish story

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_jvm_external#416]
Feature request: a way to build artifacts and make them publishable to Maven repositories.

Over the span of the last week, @cheister and @shs96c both kindly contributed PRs to do so:

https://github.com/bazelbuild/rules_jvm_external/pull/412
https://github.com/bazelbuild/rules_jvm_external/pull/413

TODO: 

- [x] Gather requirements. What are the necessary features? How would these rules work in the context of different WORKSPACES and rulesets? e.g. how artifacts should be constructed, publishing standards on Maven repositories, signing, POM file generation
- [x] Identify features implemented by @cheister and @shs96c's pull requests, and map them against the requirements. Also identify commonalities and differences between the two PRs.
- [x] Figure out a co-maintainership model of the Maven export and publishing rules. At the moment, Google doesn't use these publishing rules, so it'll help to identify co-maintainers for folks who do rely on and use this code day-to-day.

**Comment by jin** [comment]
@shs96c @cheister I wanted to write this and let you folks know that it's on my TODOs to review your PRs (schedule's bit tight at the moment), and I'd like to iron these details out at the same time. Thoughts?

**Comment by shs96c** [comment]
Where shall we be gathering these requirements? Here? Or in a Google Doc somewhere?

Assuming here, I'd suggest that the table stakes are:

- [ ] Construct a single jar from multiple `java_library`s
- [ ] Publish that jar to a local disk-based repository (the `file` scheme)

This will allow us to use fine-grained targets (eg. one per package) for efficient compilation, but still allow us to publish a single artifact (at the maven "project" level)

Ultimately, we need to be able to publish to Maven Central. A common route for this is via the Sonatype Maven repository. For this we need:

- [ ] Binary jar must contain artifacts generated by aspects (that is, not appearing in `JavaInfo.output_jars` of a rule) This is a requirement to support outputs from the `java_protobuf_library`.
- [ ] Create javadoc jars
- [ ] Create source jars
- [ ] Create SHA1 and MD5 hashes of all jars
- [ ] GPG sign all artifacts
- [ ] Publish to an HTTPS-based repository

We ran into all these issues when working on the Selenium project, and I think we've addressed each of them in #413. 

There are some problems in the code as it stands, since that PR forwards the `JavaInfo` of the inputs to the `project_jar`, which means that duplicate classes are found on the classpath.

**Comment by jin** [comment]
Thanks for listing down the requirements! Discussing them here is fine.

I've experimented with both PRs and here's what I understand:

#412:

- Generates pom.xml and pairs them with the java_library output jar of targets
- Delegates uploading to mvn

#413:

- Creates md5, sha1, POM, docjar, srcjar
- Create a valid local repo layout
- Custom binaries for publishing - doesn't use mvn
- Publishes to local and remote repository
- Signs with GPG
- Ability to exclude targets from the transitive closure

I propose that we move forward with #413, since it has a much larger set of features and has small utilities (singlejar with services support, doc generation) that we can reuse for the larger JVM ecosystem.

**Comment by cheister** [comment]
Yeah, I think #413 has many more features that what I put together.  I'll give it a try with my repo and see how it works.  In the meantime I'll decline #412
