### ISSUE TITLE
Add `maven_coordinates=` tag to targets

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_jvm_external#47]
If you want to build a jar for upload that uses these rules, you need to generate a pom file. One way to do that is with this rule https://github.com/google/bazel-common/blob/f1115e0f777f08c3cdb115526c4e663005bec69b/tools/maven/pom_file.bzl

The way this rule works is it checks your dependencies for a tag in the format `maven_coordinates={actual maven coordinates}`. It would be useful if these rules propagated this tag (or some alternative solution to this) so that pom file generation could use the same coordinate values specified only once.

**Comment by keith** [comment]
Alternatively maybe pom file generation is a rule that makes sense to have in this repository?

**Comment by keith** [comment]
If we want to go down the tag path, I've submitted a PR for it https://github.com/bazelbuild/rules_jvm_external/pull/48

**Comment by jin** [comment]
We should definitely expose the original Maven coordinate in the generated target, even if it's not used for POM file generation. Other than converting the target labels back to the Maven coordinates form, using tags SGTM, since we can record arbitrary strings in it and it doesn't interfere with analysis and execution.
