### ISSUE TITLE
Support for Kotlin Maven Build Rules

### ISSUE THREAD

**Issue by deannagarcia** [bazelbuild/rules_jvm_external#653]
I'm using the java_export build rule to create maven artifacts and it's been really helpful! Now I want to create similar maven artifacts, but for the Kotlin code I have. 

Is it possible to have a Kotlin equivalent of java_export? Or are there any plans to add this feature?

**Comment by jin** [comment]
I'm not too familiar at all with Kotlin, it's been a while since I interacted with it, and rules_kotlin. Given that rules_kotlin's libraries export the [`JavaInfo` provider](https://github.com/bazelbuild/rules_kotlin/blob/56c32cbee82473c4fc249c484e9509823ba43453/kotlin/internal/jvm/jvm.bzl#L313), I don't see any obvious technical blockers that would prevent swapping the `java_library` [here](https://github.com/bazelbuild/rules_jvm_external/blob/0fe5ce5b40900fc8ed8fb11ec977abce3c18c564/private/rules/java_export.bzl#L69-L74) for a `kt_jvm_library`, which should allow the `maven_project_jar` and `has_maven_deps` [aspect](https://github.com/bazelbuild/rules_jvm_external/blob/master/private/rules/has_maven_deps.bzl) to continue working as is.

The only question is if Kotlin jars do anything differently that we have to adapt our Maven export aspect to read [`KtJvmInfo`](https://github.com/bazelbuild/rules_kotlin/blob/56c32cbee82473c4fc249c484e9509823ba43453/kotlin/internal/defs.bzl#L25) from kotlin library targets as well.

@shs96c any thoughts?
