### ISSUE TITLE
Need option for excluding all transitive deps

### ISSUE THREAD

**Issue by twheys** [bazelbuild/rules_jvm_external#663]
Hi, my team is concerned about an increased security risk by automatically including all transitive dependencies. There doesn't seem to be a way to do this other than manually creating a list of exclusions, which can become very long and cumbersome to maintain. I'd therefore like to request an option to disable resolution of all transitive jar dependencies, so that all required compile/runtime jars must be manually added as direct dependencies.

**Comment by shs96c** [comment]
It's likely that this will lead to compilation issues, since quite often intermediate values and return types from direct dependencies can come from transitive dependencies. Even if the code compiles, it is very likely not to work. I don't think what you're requesting is a workable solution to the problem you're facing.

The bazel-ish way of handling this is to enable [--experimental_strict_java_deps](https://bazel.build/reference/command-line-reference#flag--experimental_strict_java_deps) in your `.bazelrc`, and then also set `strict_visibility` in your `maven_install`. This will require all your targets to declare their first-order dependencies, and will also force you to maintain the list of all first-order deps in your `maven_install`, increasing visibility.

In addition, if you're worried about supply-chain attacks, make sure you're using pinned dependencies, and have set the the ` fail_on_missing_checksum` flag to `True` in your `maven_install`. The sha256s of all the dependencies are then stored in your repo, and any change to an upstream dep will cause the build to fail. `coursier` (the tool we use for version resolution) should be checking the values against those stored in your Maven repo, which you should only be accessing via HTTPS. The major Maven repos (such as Maven Central) require [all uploads to be PGP signed](https://central.sonatype.org/publish/requirements/gpg/), and will have correct shasums. Attacks to your supply chain can only happen upstream of the Maven repo.

The way that Bazel works means that only those dependencies that are actually used in your build will be downloaded. You can get URLs of downloads to be rewritten using the [--experimental_downloader_config](https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config) option, which can also be used to block downloads (using Bazel's built in download mechanisms) from untrusted sites. As an example, this can be used to redirect URLs from public repos to your company's internal mirrors of those sites, which presumably include things like virus and malware scanning.

Because I don't think you'll get correctly functioning builds, and because Bazel and `rules_jvm_external` already offer several mechanisms to ensure the security of your dependency downloads, I am closing this issue. Please feel free to reopen if you disagree and can think of a way of ensuring that software built with your proposed allow list will work as intended.
