### ISSUE TITLE
Maven BOM Examples

### ISSUE THREAD

**Issue by cjohnstoniv** [bazelbuild/rules_jvm_external#866]
Is there any examples of using the maven_bom rule? I was looking to understand how all of it was intended to work between the BOM coordinates and the dependency coordinates. The dependency coordinates POM seems to depend on itself and I would expect it to be the other way around where the BOM imports the dependencies POM.

**Comment by shs96c** [comment]
There was a bug in the first release of `rules_jvm_external` with the BOM functionality, but that has been fixed in 5.1.

The way it is intended to work is that the regular BOM contains only the first-party dependencies (that is, the ones that are listed in the `java_exports` attribute of the `maven_bom` target). Any transitive dependencies (that is, dependencies of items in the `java_exports` attribute) will appear in the optionally-generated dependencies BOM.
