### ISSUE TITLE
Support for maven "RELEASE" version.

### ISSUE THREAD

**Issue by kongjiellx** [bazelbuild/rules_jvm_external#871]
I have some sub dependencies use "RELEASE" as maven version, like description in https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency
But now bazel directly try to download com.xxx:xxxx:RELEASE and can't find it.
Are there any ways to deal with my situation？

**Comment by shs96c** [comment]
The resolver we use within `rules_jvm_external` is currently [coursier](https://get-coursier.io). If that understands how to handle the `RELEASE` version, then there's nothing to do. However, I believe that `LATEST` and `RELEASE` were both removed from Maven prior to version 3, so I am unsure whether `coursier` will support that syntax. If it's something you need, then please raise a bug with that project.

Having said that, it's considered a sensible practice to pin against specific versions of your dependencies. This makes it far easier to support repeatable builds (particularly with older checkouts of your code), and `rules_jvm_external` has some tooling to make that easier.

The first bit of tooling is support for [pinning artifacts](https://github.com/bazelbuild/rules_jvm_external#pinning-artifacts-and-integration-with-bazels-downloader). This means that your project doesn't need to perform a maven dependency resolution at all --- the results of the resolution are kept in the lock file.

The second piece of tooling is the generated `:outdated` target. If you're using the default `maven` namespace, then you can get a list of artifacts to update using `bazel run @maven//:outdated` This will look for the most recent releases, as well as letting you know if there's a pre-release version of a dependency available.

With this combination of tooling, you can have faster builds (because of there being no resolution to perform), more reproducible builds (because dependencies won't change unexpectedly), and still be able to determine whether you need to update any dependencies easily.
