### ISSUE TITLE
Sha in tag 5.1 notes doesn't match with the file sha

### ISSUE THREAD

**Issue by mssoran** [bazelbuild/rules_jvm_external#878]
5.1 sha in the notes is 8c3b207722e5f97f1c83311582a6c11df99226e65e2471086e296561e57cc954

I got the following checksum when I download from https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/5.1.zip or https://github.com/bazelbuild/rules_jvm_external/archive/5.1.zip

c4cd0fd413b43785494b986fdfeec5bb47eddca196af5a2a98061faab83ed7b2

**Comment by shs96c** [comment]
The [release notes](https://github.com/bazelbuild/rules_jvm_external/releases/tag/5.1) indicate that the URL to download the artifact from has changed. It is now https://github.com/bazelbuild/rules_jvm_external/releases/download/5.1/rules_jvm_external-5.1.tar.gz and the shasum for that is `8c3b207722e5f97f1c83311582a6c11df99226e65e2471086e296561e57cc954`

We're moving away from using the zip and tarball files that are automatically generated by GitHub because they have on a few occasions changed how the compression is done, and that has changed the shasums. By using an artifact we upload and attach to the release, we can ensure that doesn't happen.
