### ISSUE TITLE
5.2 release notes checksum mismatch

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/rules_jvm_external#890]
```console
$ wget -O - 'https://github.com/bazelbuild/rules_jvm_external/archive/5.2.zip' | sha256sum
3824ac95d9edf8465c7a42b7fcb88a5c6b85d2bac0e98b941ba13f235216f313
```
but https://github.com/bazelbuild/rules_jvm_external/releases/tag/5.2 says
```python
RULES_JVM_EXTERNAL_TAG = "5.2"
RULES_JVM_EXTERNAL_SHA ="f86fd42a809e1871ca0aabe89db0d440451219c3ce46c58da240c7dcdc00125f"
```

**Comment by shs96c** [comment]
You have the wrong URL: https://github.com/bazelbuild/rules_jvm_external/releases/download/5.2/rules_jvm_external-5.2.tar.gz is the correct one, as mentioned in the release notes.

We don't use the auto-generated bundles any more because GitHub occasionally change how they're generated, and that breaks builds.
